name: .NET Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add .NET tools to PATH
      run: echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

    - name: Restore dependencies
      run: dotnet restore ./DataNexus/DataNexus.csproj

    - name: Setup SonarCloud Analysis
      run: dotnet-sonarscanner begin /k:"Wolf1904_DataNexus" /o:"wolf1904" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Build solution
      run: dotnet build ./DataNexus/DataNexus.csproj --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test ./DataNexus/DataNexus.csproj --no-build --configuration Release --collect:"Code coverage"

    - name: End SonarCloud Analysis
      run: dotnet-sonarscanner end
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
